### ISSUE TITLE
Problem with captions

### ISSUE THREAD

**Issue by mestarh** [DevExpress-Examples/XAF_how-to-represent-an-enumeration-property-via-a-drop-down-box-with-check-boxes-e689#3]
Hi, 
I found there is a problem when the enum captions contains another name. 
For example:
Air, Air/Water, Air/Ground.

The replace method working on captions is insufficient for this example and throws error....

**Comment by mestarh** [comment]
I've changed method ConvertFromLocalizedString() to something like that:

private string ConvertFromLocalizedString(string localizedString)
{
    string[] captions = localizedString.Split(',');
    string result = string.Empty;

    foreach(object enumValue in EnumDescriptor.Values)
    {
        string enumCaption = EnumDescriptor.GetCaption(enumValue);

        if(captions.Any(x=>x.Trim() == enumCaption.Trim()))
        {
            if(string.IsNullOrEmpty(result))
                result += enumValue.ToString();
            else
                result += string.Format("{0} {1}",',',enumValue.ToString());
        }

    }
    return result;
}

**Comment by AndreyKozhevnikov** [comment]
Hello,
Thank you for your report. I added your code to our repository.
Andrey

#4
